### ISSUE TITLE
YIKES... prints non-serializable value with ~v, not ~e?

### ISSUE THREAD

**Issue by jbclements** [bennn/with-cache#10]
It appears to me when with-cache is used with a non-serializable value, it prints an error message...containing the entire unserializable value. The reason I'm likely to use with-cache is because I have a multi-megabyte value, so printing the entire thing out is going to absolutely destroy the DrRacket error output spool; right now, my DrR is totally wedged trying to print out a gigantic value, and if it's not unstuck by the time I'm done filing this PR, I"m just going to kill the whole process.

I'm guessing the fix is a trivial replacement of ~v (or ~a or whatever) with ~e, which will truncate the error output.

Let me know if you want steps to reproduce.

**Comment by bennn** [comment]
yikes for sure, should be fixed now

**Comment by jbclements** [comment]
> On Nov 27, 2016, at 10:54, Benjamin Greenman <notifications@github.com> wrote:
> 
> yikes for sure, should be fixed now

Thanks!

John
