### ISSUE TITLE
a gentle suggestion about the API

### ISSUE THREAD

**Issue by mbutterick** [bennn/with-cache#17]
IIUC, the `with-` naming convention typically denotes “this item is going to be passed as extra input to the thunk at the end by way of a parameter.” 

For instance, `with-input-from-file` provides a value that is then stuffed into `current-input-port`.

But that’s not really what's happening in `with-cache`:

```racket
(define fish
  (with-cache (cachefile "stdfish.rktd")
    (λ () (standard-fish 100 50))))
```

The cache is not the input to the thunk. 

Rather, it’s closer to the usual `hash-ref` idiom:

```racket
(define my-hash (make-hash))
(define fish 
  (hash-ref my-hash
    (λ () (standard-fish 100 50))))
``` 

Which suggests analogous naming, for instance:

```racket
(define my-cache (make-cache "stdfish.rktd"))
(define fish
  (cache-ref my-cache
    (λ () (standard-fish 100 50))))
```

Or going a step further, I don’t see why `with-cache` couldn’t be implemented as a hash impersonator:

```racket
(define my-hash (make-hash-cached "stdfish.rktd"))
(define fish 
  (hash-ref my-hash
    (λ () (standard-fish 100 50))))
``` 

Which makes it an easier drop-in replacement for a hash.

**Comment by bennn** [comment]
I'm happy to alias `with-cache` to `cache-ref`.

I'm not convinced that the analogy to `hash-ref` is useful. Hashes have multiple key/value pairs, but caches have one value that might be invalid (the above calls to `hash-ref` look nice, but they're passing a function as the key).
Also I usually call `with-cache` with a few keys, and that puts me in less of a `hash-ref` mood.

I think of `with-input-from-file` and `with-cache` as setting up a context, just like Python's `with` form.

**Comment by mbutterick** [comment]
> the above calls to hash-ref look nice, but they're passing a function as the key

Whoops, that’s my error. OK, this idea was officially half-baked. Disregard.
