### ISSUE TITLE
the case for more nuanced comparison of #:keys?

### ISSUE THREAD

**Issue by mbutterick** [bennn/with-cache#21]
I’d like to use `with-cache` to store font metrics, where the file cache contains a hashtable of glyph pairs mapped to their widths. So my ideal use of the cache goes like this:

1) Make a list of all the glyph pairs in the text I want to measure.

2) If the cache contains entries for my pairs — that is, my pairs are a subset of the pairs in the cache — load the cache and use it.

3) If the cache is missing pairs, invalidate the cache (or better: load the cache as a hashtable, update it, and write it out again).

I gather that I can use `#:keys` to store the list of pairs as an invalidation key. But of `current-cache-keys`, the docs say:

> The values in *current-cache-keys* are computations. We run these computations once before writing a cache file and save the result. We run these computations again when reading the cache file; **if the new results match the saved results,** the cache file is valid. Otherwise, the cache file is outdated and with-cache will discard it.

I assume “match” here means “the same, in the sense of `equal?`”. 

In my case, this is too rigid. It would be useful to have, say, a `#:key-compare` option that accepts a 2-arity function that compares the old and new keys. (Similar to the comparision procedure passed to `sort`.) It could default to `equal?`.

Then, in this case, I could take my input pairs, and use `#:key-compare` to compare them against the current keys with `member` to see if I have a subset.

**Comment by bennn** [comment]
I agree with the spirit of this issue

but are you sure you don't want `db` ?

Two things that are weird to me:
- storing (a copy of) the actual data as a cache key
- using subset to compare keys (instead of some equality)

and "subset" really makes me think of a database.

**Comment by mbutterick** [comment]
> but are you sure you don't want db ?

Now you have two problems, etc.

> Two things that are weird to me:
> storing (a copy of) the actual data as a cache key
> using subset to compare keys (instead of some equality)

The more expensive a cached computation is, the more one is reasonably willing to spend to avoid invalidating the cache. In essence, it models a lazily computed lookup table.

**Comment by bennn** [comment]
One more question: can a glyph pair's width ever be invalid? Or is either present or missing.

**Comment by mbutterick** [comment]
Yes the cache data can be obsolete, but I would check that separately. 

For instance, the whole key-checking logic in this case would go like this:

1) Compare the modification time for the cache vs. that of the font that provides the metrics. 

2) If the font is newer, then invalidate the whole cache. 

3) If the font is older, then assume the cache measurements are valid, and proceed to checking whether the glyph pairs are a subset of those in the cache.

BTW2, the subset operation is a tolerable cost because it’s logarithmically proportional to the length of the text being measured.

**Comment by bennn** [comment]
I'm not worried about cost. My problem is that I believe cache keys should only be checked for equality --- anything else is a "type error". (And I still think `db` or even `mongodb` is a better tool for this job.)

But with #22 merged, you'll be able to do (EDIT, its not quite `subset?`):

```
(with-cache #:keys-equal? (lambda (x y) (subset? y x)) ....)
```

**Comment by bennn** [comment]
Closing because #22 added a "key-compare option" called `#:keys-equal?`
