### ISSUE TITLE
with-cache cannot ever read (fasl) cache files with Racket 7.

### ISSUE THREAD

**Issue by LeifAndersen** [bennn/with-cache#23]
I have the following program

```
#lang racket
(require with-cache pict)
(with-cache "foo.rktd"
  (λ ()
    (circle 100)))
```

The first time the file runs a cache is built. However, when I run it the second time, it fails to read the cachefile, and ends up generating a new one. Here is the error message it gives:

```
with-cache: Failed to read cache file 'foo.rktd', got exception:
fasl-read: error parsing fasl stream;
 unrecognized prefix
```

This _might_ be a problem with fasl changes in Racket 7. I will investigate further.

**Comment by bennn** [comment]
Dear Ben,

Try re-running your libraries that depend on `with-cache`. Maybe `raco pkg remove` can help find the libraries?

**Comment by LeifAndersen** [comment]
It also looks like its not a pict specific problem, as this code has the same problem:

```
(with-cache "bar.rktd"
  (λ () 5))
```

**Comment by LeifAndersen** [comment]
Also, this one _does_ seem to work:

```
(define sfx (s-exp->fasl '(1 2 3)))
(fasl->s-exp sfx)
```

**Comment by LeifAndersen** [comment]
It looks like the cause is the comment that is added to the top of the cache file.

For example, both above examples work if I manually remove the line:

```
;; This file was generated by the `with-cache` library on 2018-03-21
```

**Comment by bennn** [comment]
https://github.com/bennn/with-cache/commit/52e4189481715a0b12df504c693ee44b26b4382f should fix this, but I'll run more tests before closing this issue
